#This file is my FINAL CODE not in the folder named Bobagang one.
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets
from Order import Ui_OrderWindow

class Ui_LoginWindow(object):
#open Order Window
    def open_OrderWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_OrderWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(560, 740)
        LoginWindow.setStyleSheet("QWidget#centralwidget{background-color: rgb(51, 58, 108);}")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 60, 191, 81))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 48pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 240, 201, 31))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 390, 201, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 170, 411, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.Username_enter = QtWidgets.QLineEdit(self.centralwidget)
        self.Username_enter.setGeometry(QtCore.QRect(50, 310, 461, 50))
        self.Username_enter.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.Username_enter.setText("")
        self.Username_enter.setObjectName("Username_enter")
        self.Password_enter = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_enter.setGeometry(QtCore.QRect(50, 450, 461, 50))
        self.Password_enter.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.Password_enter.setObjectName("Password_enter")
        self.Login_button = QtWidgets.QPushButton(self.centralwidget)
        self.Login_button.setGeometry(QtCore.QRect(420, 660, 121, 61))
        self.Login_button.setStyleSheet("\n"
"background-color: rgb(250, 193, 114);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.Login_button.setObjectName("Login_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(20, 640, 141, 81))
        self.exit_button.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.exit_button.setObjectName("exit_button")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(180, 540, 331, 31))
        self.error.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.error.setObjectName("error")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "Login"))
        self.label_2.setText(_translate("LoginWindow", "Username :"))
        self.label_3.setText(_translate("LoginWindow", "Password :"))
        self.label_4.setText(_translate("LoginWindow", "*THIS IS FOR SELLERS ONLY !!!!"))
        self.Login_button.setText(_translate("LoginWindow", "Login"))
        self.exit_button.setText(_translate("LoginWindow", "Exit"))

#buttons
        self.Login_button.clicked.connect(self.loginfunction)
        self.exit_button.clicked.connect(LoginWindow.close)
#loginfunction to login and go to OrderWindow only with correct username, password
    def loginfunction(self):
            username = self.Username_enter.text()
            password = self.Password_enter.text()

            if len(username) == 0 or len(password) == 0:
                    self.error.setText("*Please fill in all inputs.")
            elif username != "helloworld" or password != "12345678":
                    self.error.setText("*Incorrect username or password")
            else:
                  self.window = QtWidgets.QMainWindow()
                  self.ui = Ui_OrderWindow()
                  self.ui.setupUi(self.window)
                  self.window.show()
  
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())

