#This file is my FINAL CODE not in the folder named Bobagang one.
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Order.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

##Create a database1 = name_list
conn = sqlite3.connect('namelist.db')
c = conn.cursor()
# Create a table
c.execute("""CREATE TABLE if not exists name_list(
    list_item text)
    """)
conn.commit()
conn.close()

##Create a database2 = order_list
conn2 = sqlite3.connect('orderlist.db')
c2 = conn2.cursor()
c2.execute("""CREATE TABLE if not exists order_list(
    list_item2 text)
    """)
conn2.commit()
conn2.close()

#######################################################################################################
class Ui_OrderWindow(object):
    def setupUi(self, OrderWindow):
        OrderWindow.setObjectName("OrderWindow")
        OrderWindow.resize(560, 740)
        OrderWindow.setStyleSheet("QWidget#centralwidget{background-color: rgb(51, 58, 108);}")
        self.centralwidget = QtWidgets.QWidget(OrderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 70, 161, 61))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 36pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.Done_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.done())
        self.Done_button.setGeometry(QtCore.QRect(450, 120, 91, 41))
        self.Done_button.setStyleSheet("background-color: rgb(137, 213, 201);\n"
"font: 15pt \"MS Shell Dlg 2\";")
        self.Done_button.setObjectName("Done_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(400, 640, 141, 81))
        self.exit_button.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.exit_button.setObjectName("exit_button")
        self.name_list = QtWidgets.QListWidget(self.centralwidget)
        self.name_list.setGeometry(QtCore.QRect(10, 200, 191, 421))
        self.name_list.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.name_list.setObjectName("name_list")
        self.order_list = QtWidgets.QListWidget(self.centralwidget)
        self.order_list.setGeometry(QtCore.QRect(200, 200, 351, 421))
        self.order_list.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.order_list.setObjectName("order_list")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 71, 31))
        self.label_2.setStyleSheet("color: rgb(250, 193, 114);\n"
"font: 17pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 160, 71, 31))
        self.label_3.setStyleSheet("color: rgb(250, 193, 114);\n"
"font: 17pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(20, 650, 121, 61))
        self.save_button.setStyleSheet("background-color: rgb(250, 193, 114);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.save_button.setObjectName("save_button")
        OrderWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrderWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderWindow)

    def retranslateUi(self, OrderWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderWindow.setWindowTitle(_translate("OrderWindow", "MainWindow"))
        self.label.setText(_translate("OrderWindow", "Orders"))
        self.Done_button.setText(_translate("OrderWindow", "Done"))
        self.exit_button.setText(_translate("OrderWindow", "Exit"))
        self.label_2.setText(_translate("OrderWindow", "Name"))
        self.label_3.setText(_translate("OrderWindow", "Order"))
        self.save_button.setText(_translate("OrderWindow", "Save"))

        self.exit_button.clicked.connect(OrderWindow.close)
        self.save_button.clicked.connect(self.save_db)
        self.save_button.clicked.connect(self.save_db2)

## Grab all the items from the database1
        self.grab_all()
    # Grab items from database1
    def grab_all(self):
        conn = sqlite3.connect('namelist.db')
        c = conn.cursor()
        c.execute("SELECT * FROM name_list")
        records = c.fetchall()
        conn.commit()
        conn.close()
        # Loop thru records and add to screen
        for record in records:
            self.name_list.addItem(str(record[0]))

##Grab all the items from the database2
        self.grab_all2()
    # Grab items from database2
    def grab_all2(self):
        conn2 = sqlite3.connect('orderlist.db')
        c2 = conn2.cursor()
        c2.execute("SELECT * FROM order_list")
        recordsss = c2.fetchall()
        conn2.commit()
        conn2.close()
        for recordss in recordsss:
            self.order_list.addItem(str(recordss[0]))
        
#####################################################################
        
##Save name_list To The Database1
    def save_db(self):
        # Create a database or connect to one
        conn = sqlite3.connect('namelist.db')
        # Create a cursor
        c = conn.cursor()
        # Delete everything in the database table
        c.execute('DELETE FROM name_list;',) 
        # Create Blank List To Hold Items
        items = []
        # Loop through the listWidget and pull out each item
        for index in range(self.name_list.count()):
            items.append(self.name_list.item(index))
        for item in items:
            #print(item.text())
            # Add stuff to the table
            c.execute("INSERT INTO name_list VALUES (:item)",
                {
                    'item': item.text(),
                })
        # Commit the changes
        conn.commit()
        # Close our connection
        conn.close()  
             
##Save order_list To The Database2
    def save_db2(self):
        # Create another database
        conn2 = sqlite3.connect('orderlist.db')
        c2 = conn2.cursor()
        c2.execute('DELETE FROM order_list;',)
        itemsss = []
        for index in range(self.order_list.count()):
            itemsss.append(self.order_list.item(index))
        for itemss in itemsss:
            c2.execute("INSERT INTO order_list VALUES (:itemss)",
                {
                'itemss': itemss.text(),
                })
        conn2.commit()
        conn2.close()  

###########################################################################

#Done_button select name, order to delete when done
    def done(self):
        clicked = self.name_list.currentRow()
        self.name_list.takeItem(clicked)
        clicked = self.order_list.currentRow()
        self.order_list.takeItem(clicked)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderWindow = QtWidgets.QMainWindow()
    ui = Ui_OrderWindow()
    ui.setupUi(OrderWindow)
    OrderWindow.show()
    sys.exit(app.exec_())
